# name: cicd pipeline flow

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the site in the jekyll/builder container
#       run: |
#         docker run \
#         -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#         jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
#         name: Cypress CI

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - ./run_tests.sh
  tags:
    - docker

build:
  stage: build
  script:
    - ./build.sh
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - ./deploy.sh
  tags:
    - docker
